### ISSUE TITLE
Add collaborators to npm

### ISSUE THREAD

**Issue by pierceray** [wellington/wellington-bin#8]
I don't have access to publish wellington-bin to npm.  Can you add me as another owner.

https://docs.npmjs.com/cli/owner

`npm owner add pierceray wellington-bin`

**Comment by andystalick** [comment]
Done, looks like it worked.

**Comment by pierceray** [comment]
👍 Looks like it worked.  I published 1.3.0, but https://www.npmjs.com/package/wellington-bin is still showing the old one, but `npm show wellington-bin` shows the right info.
